### ISSUE TITLE
Create a Twitter developer account

### ISSUE THREAD

**Issue by cedricgrothues** [MLH-Fellowship/0.2.1-donation-trigger#1]
Twitter requires users to apply for a developer account (https://developer.twitter.com/en/apply-for-access) to be able to use their APIs.

Does anyone have an account that is already approved?

**Comment by barronwei** [comment]
@ianjennings Do you know anybody with a developer account that we could use in the meantime? Looks like applying for one may take a while.

**Comment by cedricgrothues** [comment]
twitter approved the dev account application 🎉
