### ISSUE TITLE
Implement User Authorization

### ISSUE THREAD

**Issue by erin2722** [MLH-Fellowship/0.2.1-donation-trigger#6]
Using Amplify, Twitter, or Instagram depending on which provides the most functionality

**Comment by barronwei** [comment]
After digging around the [Twitter API user auth flow](https://developer.twitter.com/en/docs/basics/authentication/oauth-1-0a/obtaining-user-access-tokens), auth at the simplest level could be a single button on our UI.

We could persist the token and secret in the user browser through cookies, and store data in our backend by Twitter handle, which we query the Twitter API for each time the user accesses our site.
